#
# broker.yml
#
# Simple yaml file for the env specific configuration of the broker connections.
# See the wiki for more information: http://code.google.com/p/activemessaging/wiki/Configuration
#
development:
    adapter: stomp
    login: root
    passcode: 
    host: localhost
    port: 61613   
    reliable: true
    reconnectDelay: 5
    
test:
    adapter: test
    reliable: false

production:
    adapter: stomp
    login: root
    passcode: 
    host: localhost
    port: 61613   
    reliable: true
    reconnectDelay: 5
